"""Never auto-pick a calendar the user cannot write to.

The reported symptom was "Nextcloud still doesn't allow write". The cause was
ordering: discovery sorted by display name, "Contact birthdays" sorts before
"Personal", and everything that needed a calendar took the first one. That
calendar is generated by Nextcloud from your contacts and is read-only, so the
write came back 403 — which reads like broken credentials, not like a bad pick.
"""
from __future__ import annotations

import asyncio

import pytest

from tools.nextcloud import parse_dav_multistatus, register_nextcloud_tools


def _cal(href, name, comps, privileges):
    privs = "".join(f"<d:privilege><d:{p}/></d:privilege>" for p in privileges)
    comp_xml = "".join(f'<cal:comp name="{c}"/>' for c in comps)
    return f"""
 <d:response>
  <d:href>{href}</d:href>
  <d:propstat><d:prop>
    <d:displayname>{name}</d:displayname>
    <d:resourcetype><d:collection/><cal:calendar/></d:resourcetype>
    <d:current-user-privilege-set>{privs}</d:current-user-privilege-set>
    <cal:supported-calendar-component-set>{comp_xml}</cal:supported-calendar-component-set>
  </d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat>
 </d:response>"""


def _multistatus(*responses):
    return ('<?xml version="1.0"?><d:multistatus xmlns:d="DAV:" '
            'xmlns:cal="urn:ietf:params:xml:ns:caldav">' + "".join(responses) + "</d:multistatus>")


STOCK = _multistatus(
    _cal("/remote.php/dav/calendars/u/contact_birthdays/", "Contact birthdays",
         ["VEVENT"], ["read"]),
    _cal("/remote.php/dav/calendars/u/personal/", "Personal",
         ["VEVENT", "VTODO"], ["read", "write"]),
)


def test_privileges_are_parsed():
    rows = {e["displayname"]: e for e in parse_dav_multistatus(STOCK)}
    assert rows["Contact birthdays"]["writable"] is False
    assert rows["Personal"]["writable"] is True


def test_absent_privileges_are_not_treated_as_read_only():
    """A server that does not report privileges must not have every calendar
    written off — only an explicit denial counts."""
    xml = _multistatus(
        '<d:response><d:href>/c/x/</d:href><d:propstat><d:prop>'
        '<d:displayname>Plain</d:displayname>'
        '<d:resourcetype><d:collection/><cal:calendar/></d:resourcetype>'
        '</d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response>')
    assert parse_dav_multistatus(xml)[0]["writable"] is None


# ── the resolver, driven through the registered tools ────────────────────────

class _FakeResponse:
    def __init__(self, text):
        self.text = text
        self.status_code = 207

    def raise_for_status(self):
        pass


class _FakeClient:
    """Answers the discovery PROPFIND; records any PUT."""

    puts: list = []

    def __init__(self, *a, **kw):
        pass

    async def __aenter__(self):
        return self

    async def __aexit__(self, *a):
        return False

    async def request(self, method, url, **kw):
        return _FakeResponse(STOCK)

    async def put(self, url, **kw):
        _FakeClient.puts.append(url)
        return _FakeResponse("")


@pytest.fixture
def nc(monkeypatch):
    from config import cfg
    import tools.nextcloud as N

    for k, v in (("nextcloud_url", "https://cloud.example.com"),
                 ("nextcloud_username", "u"), ("nextcloud_password", "p")):
        monkeypatch.setattr(cfg, k, v, raising=False)
    monkeypatch.setattr(N.httpx, "AsyncClient", _FakeClient)
    _FakeClient.puts = []

    from mcp.server.fastmcp import FastMCP

    m = FastMCP("t")
    register_nextcloud_tools(m)
    return m


def _call(m, name, args):
    return asyncio.run(m._tool_manager.call_tool(name, args))


def test_list_calendars_puts_writable_first_and_flags_the_rest(nc):
    out = str(_call(nc, "nextcloud_list_calendars", {}))
    assert out.index("personal") < out.index("contact_birthdays"), \
        "the writable calendar must be offered first"
    assert "read-only" in out
    assert "do not write here" in out


def test_add_event_lands_on_the_writable_calendar(nc):
    """No calendar named, so the tool has to choose — and must not choose the
    one it cannot write to."""
    out = str(_call(nc, "nextcloud_add_event", {"params": {
        "title": "Dentist", "date": "2026-08-10", "calendar": ""}}))
    assert _FakeClient.puts, "no PUT was made"
    assert "/personal/" in _FakeClient.puts[0], _FakeClient.puts
    assert "contact_birthdays" not in _FakeClient.puts[0]
    assert "Dentist" in out


def test_add_event_honours_an_explicit_choice_but_warns(nc):
    """Refusing to write where you were told to write is worse than warning."""
    out = str(_call(nc, "nextcloud_add_event", {"params": {
        "title": "Birthday", "date": "2026-08-10", "calendar": "contact_birthdays"}}))
    assert "/contact_birthdays/" in _FakeClient.puts[0]
    assert "read-only" in out and "likely be refused" in out


def test_an_unknown_calendar_falls_back_and_says_which(nc):
    out = str(_call(nc, "nextcloud_add_event", {"params": {
        "title": "Thing", "date": "2026-08-10", "calendar": "nope"}}))
    assert "/personal/" in _FakeClient.puts[0]
    assert "'nope' is not a calendar" in out


def test_no_deprecated_utcnow_remains():
    """utcnow() is deprecated and returns a naive datetime that claims to be UTC."""
    import pathlib

    import tools.nextcloud as N

    assert "utcnow()" not in pathlib.Path(N.__file__).read_text(encoding="utf-8")
