"""Canonical built-in service and capability metadata."""

from __future__ import annotations

from config import cfg

SERVICES: list[dict] = [
  # â•â•â•â•â•â•â•â• SELF-HOSTED â•â•â•â•â•â•â•â•
  {"id":"jellyfin","label":"Jellyfin","icon":"🎬","tag":"media","section":"selfhosted",
   "desc":"Media server — movies, TV, music",
   "config_keys":[("JELLYFIN_URL","Server URL","http://192.168.1.111:8096",False),("JELLYFIN_API_KEY","API Key","",True),("JELLYFIN_USER_ID","User ID","",False)],
   "health_url":lambda: cfg.jellyfin_url+"/health","health_headers":lambda: {"X-Emby-Token":cfg.jellyfin_api_key},
   "configured_keys":("jellyfin_url","jellyfin_api_key"),
   "tools":[{"name":"jellyfin_search","label":"Search Library","params":[("query","Search term","text"),("limit","Max results","number")]},
            {"name":"jellyfin_recently_added","label":"Recently Added","params":[("limit","Max results","number")]}]},

  {"id":"sonarr","label":"Sonarr","icon":"📺","tag":"arr","section":"selfhosted",
   "desc":"TV show management & downloading",
   "config_keys":[("SONARR_URL","Server URL","http://192.168.1.111:8989",False),("SONARR_API_KEY","API Key","",True)],
   "health_url":lambda: cfg.sonarr_url+"/api/v3/health","health_headers":lambda: {"X-Api-Key":cfg.sonarr_api_key},
   "configured_keys":("sonarr_url","sonarr_api_key"),
   "tools":[{"name":"sonarr_search_show","label":"Search Show","params":[("query","Show name","text")]},
            {"name":"sonarr_list_series","label":"All Series","params":[]},
            {"name":"sonarr_add_series","label":"Add Series","params":[("tvdb_id","TVDB ID","number"),("title","Title","text")]},
            {"name":"sonarr_queue","label":"Queue","params":[]},
            {"name":"sonarr_calendar","label":"Upcoming (7d)","params":[]},
            {"name":"sonarr_missing","label":"Missing Episodes","params":[]}]},

  {"id":"radarr","label":"Radarr","icon":"🎥","tag":"arr","section":"selfhosted",
   "desc":"Movie management & downloading",
   "config_keys":[("RADARR_URL","Server URL","http://192.168.1.111:7878",False),("RADARR_API_KEY","API Key","",True)],
   "health_url":lambda: cfg.radarr_url+"/api/v3/health","health_headers":lambda: {"X-Api-Key":cfg.radarr_api_key},
   "configured_keys":("radarr_url","radarr_api_key"),
   "tools":[{"name":"radarr_search_movie","label":"Search Movie","params":[("query","Movie name","text")]},
            {"name":"radarr_list_movies","label":"All Movies","params":[]},
            {"name":"radarr_add_movie","label":"Add Movie","params":[("tmdb_id","TMDB ID","number"),("title","Title","text")]},
            {"name":"radarr_queue","label":"Queue","params":[]}]},

  {"id":"lidarr","label":"Lidarr","icon":"🎵","tag":"arr","section":"selfhosted",
   "desc":"Music management & downloading",
   "config_keys":[("LIDARR_URL","Server URL","http://192.168.1.111:8686",False),("LIDARR_API_KEY","API Key","",True)],
   "health_url":lambda: cfg.lidarr_url+"/api/v3/health","health_headers":lambda: {"X-Api-Key":cfg.lidarr_api_key},
   "configured_keys":("lidarr_url","lidarr_api_key"),
   "tools":[{"name":"lidarr_search_artist","label":"Search Artist","params":[("query","Artist name","text")]},
            {"name":"lidarr_list_artists","label":"All Artists","params":[]},
            {"name":"lidarr_queue","label":"Queue","params":[]}]},

  {"id":"jellyseerr","label":"Jellyseerr","icon":"📋","tag":"media","section":"selfhosted",
   "desc":"Content request management",
   "config_keys":[("JELLYSEERR_URL","Server URL","http://192.168.1.111:5055",False),("JELLYSEERR_API_KEY","API Key","",True)],
   "health_url":lambda: cfg.jellyseerr_url+"/api/v1/status","health_headers":lambda: {"X-Api-Key":cfg.jellyseerr_api_key},
   "configured_keys":("jellyseerr_url","jellyseerr_api_key"),
   "tools":[{"name":"jellyseerr_request","label":"Request Content","params":[("media_type","Type","text"),("media_id","ID","number")]},
            {"name":"jellyseerr_requests","label":"All Requests","params":[]}]},

  {"id":"qbittorrent","label":"qBittorrent","icon":"⬇️","tag":"media","section":"selfhosted",
   "desc":"Torrent download client",
   "config_keys":[("QBITTORRENT_URL","Server URL","http://192.168.1.111:8080",False),("QBITTORRENT_USERNAME","Username","admin",False),("QBITTORRENT_PASSWORD","Password","",True)],
   "health_url":lambda: cfg.qbittorrent_url+"/api/v2/app/version","health_headers":lambda: {},
   "configured_keys":("qbittorrent_url","qbittorrent_password"),
   "tools":[{"name":"qbittorrent_list","label":"Active Downloads","params":[]},
            {"name":"qbittorrent_pause","label":"Pause","params":[("hash","Torrent hash","text")]},
            {"name":"qbittorrent_resume","label":"Resume","params":[("hash","Torrent hash","text")]},
            {"name":"qbittorrent_delete","label":"Delete","params":[("hash","Torrent hash","text")]}]},

  {"id":"immich","label":"Immich","icon":"📸","tag":"photos","section":"selfhosted",
   "desc":"Self-hosted photo & video library",
   "config_keys":[("IMMICH_URL","Server URL","http://192.168.1.111:2283",False),("IMMICH_API_KEY","API Key","",True)],
   "health_url":lambda: cfg.immich_url+"/api/server/ping","health_headers":lambda: {"x-api-key":cfg.immich_api_key},
   "configured_keys":("immich_url","immich_api_key"),
   "tools":[{"name":"immich_search","label":"Smart Search","params":[("query","Query","text")]},
            {"name":"immich_list_albums","label":"Albums","params":[]},
            {"name":"immich_get_memories","label":"Today Memories","params":[]},
            {"name":"immich_list_people","label":"People","params":[]},
            {"name":"immich_search_by_metadata","label":"Search by Date/City","params":[("year","Year","number"),("city","City","text")]}]},

  {"id":"homeassistant","label":"Home Assistant","icon":"🏠","tag":"home","section":"selfhosted",
   "desc":"Home automation platform",
   "config_keys":[("HA_URL","Server URL","http://192.168.1.X:8123",False),("HA_TOKEN","Long-Lived Token","",True)],
   "health_url":lambda: cfg.ha_url+"/api/","health_headers":lambda: {"Authorization":f"Bearer {cfg.ha_token}"},
   "configured_keys":("ha_url","ha_token"),
   "tools":[{"name":"ha_get_states","label":"All States","params":[]},
            {"name":"ha_search_entities","label":"Search Entities","params":[("query","Search","text")]},
            {"name":"ha_turn_on","label":"Turn On","params":[("entity_id","Entity ID","text")]},
            {"name":"ha_turn_off","label":"Turn Off","params":[("entity_id","Entity ID","text")]},
            {"name":"ha_call_service","label":"Call Service","params":[("domain","Domain","text"),("service","Service","text"),("entity_id","Entity ID","text")]}]},

  {"id":"nextcloud","label":"Nextcloud","icon":"☁️","tag":"cloud","section":"selfhosted",
   "desc":"Files, calendar, contacts, notes",
   "config_keys":[("NEXTCLOUD_URL","Server URL","http://192.168.1.111/nextcloud",False),("NEXTCLOUD_USERNAME","Username","",False),("NEXTCLOUD_PASSWORD","Password / App Token","",True)],
   "health_url":lambda: cfg.nextcloud_url+"/status.php","health_headers":lambda: {},
   "configured_keys":("nextcloud_url","nextcloud_username","nextcloud_password"),
   "tools":[{"name":"nextcloud_list_calendars","label":"Calendars","params":[]},
            {"name":"nextcloud_get_events","label":"Get Events","params":[("calendar","Calendar slug","text"),("days_ahead","Days ahead","number")]},
            {"name":"nextcloud_add_event","label":"Add Event","params":[("calendar","Slug","text"),("title","Title","text"),("date","YYYY-MM-DD","text"),("start_time","HH:MM","text")]},
            {"name":"nextcloud_get_tasks","label":"Tasks","params":[("list_name","List slug","text")]},
            {"name":"nextcloud_add_task","label":"Add Task","params":[("title","Title","text"),("due_date","Due date","text")]},
            {"name":"nextcloud_list_contacts","label":"Contacts","params":[]},
            {"name":"nextcloud_search_contacts","label":"Search Contacts","params":[("query","Name/email","text")]},
            {"name":"nextcloud_add_contact","label":"Add Contact","params":[("name","Full name","text"),("email","Email","text")]},
            {"name":"nextcloud_list_files","label":"Files","params":[("path","Folder path","text")]},
            {"name":"nextcloud_get_notes","label":"Notes","params":[]},
            {"name":"nextcloud_create_note","label":"Create Note","params":[("title","Title","text"),("content","Content","text")]},
            {"name":"nextcloud_get_user_info","label":"User Info","params":[]},
            {"name":"nextcloud_get_activity","label":"Activity","params":[]},
            {"name":"nextcloud_list_shares","label":"Shares","params":[]}]},

  {"id":"habitica","label":"Habitica","icon":"🎮","tag":"personal","section":"selfhosted",
   "desc":"Habit & task RPG (self-hosted)",
   "config_keys":[("HABITICA_URL","Server URL","http://192.168.1.111:3030",False),("HABITICA_USER_ID","User ID","",False),("HABITICA_API_TOKEN","API Token","",True)],
   "health_url":lambda: cfg.habitica_url+"/api/v4/status","health_headers":lambda: {},
   "configured_keys":("habitica_url","habitica_user_id","habitica_api_token"),
   "tools":[{"name":"habitica_get_stats","label":"Character Stats","params":[]},
            {"name":"habitica_get_tasks","label":"All Tasks","params":[]},
            {"name":"habitica_score_task","label":"Score Task","params":[("task_id","Task ID","text")]},
            {"name":"habitica_add_todo","label":"Add To-Do","params":[("text","Task name","text")]},
            {"name":"habitica_add_habit","label":"Add Habit","params":[("text","Habit name","text")]}]},

  {"id":"n8n","label":"n8n","icon":"⚡","tag":"automation","section":"selfhosted",
   "desc":"Workflow automation",
   "config_keys":[("N8N_URL","Server URL","http://192.168.1.111:5678",False),("N8N_API_KEY","API Key","",True)],
   "health_url":lambda: cfg.n8n_url+"/healthz","health_headers":lambda: {},
   "configured_keys":("n8n_url","n8n_api_key"),
   "tools":[{"name":"n8n_list_workflows","label":"All Workflows","params":[]},
            {"name":"n8n_get_executions","label":"Recent Executions","params":[]},
            {"name":"n8n_trigger_webhook","label":"Trigger Webhook","params":[("webhook_path","Path","text")]}]},

  {"id":"ntfy","label":"Ntfy","icon":"🔔","tag":"notifications","section":"selfhosted",
   "desc":"Push notification server",
   "config_keys":[("NTFY_URL","Server URL","http://192.168.1.111:5050",False),("NTFY_USERNAME","Username (required to mark configured)","",False),("NTFY_PASSWORD","Password / token","",True),("NTFY_DEFAULT_TOPIC","Default Topic","assistant",False)],
   "health_url":lambda: cfg.ntfy_url+"/v1/health","health_headers":lambda: ({"Authorization": f"Basic {__import__('base64').b64encode((cfg.ntfy_username + ':' + cfg.ntfy_password).encode()).decode()}"} if cfg.ntfy_username else {}),
   "configured_keys":("ntfy_url","ntfy_username"),
   "tools":[{"name":"ntfy_send","label":"Send Notification","params":[("message","Message","text"),("topic","Topic","text"),("title","Title","text")]}]},

  {"id":"syncthing","label":"Syncthing","icon":"🔄","tag":"sync","section":"selfhosted",
   "desc":"Continuous file sync",
   "config_keys":[("SYNCTHING_URL","Server URL","http://192.168.1.111:8384",False),("SYNCTHING_API_KEY","API Key","",True)],
   "health_url":lambda: cfg.syncthing_url+"/rest/system/ping","health_headers":lambda: {"X-API-Key":cfg.syncthing_api_key},
   "configured_keys":("syncthing_url","syncthing_api_key"),
   "tools":[{"name":"syncthing_status","label":"Status","params":[]},
            {"name":"syncthing_folders","label":"Folders","params":[]},
            {"name":"syncthing_devices","label":"Devices","params":[]},
            {"name":"syncthing_rescan","label":"Rescan Folder","params":[("folder_id","Folder ID","text")]}]},

  {"id":"obsidian","label":"Obsidian","icon":"📝","tag":"notes","section":"selfhosted",
   "desc":"Local REST API plugin",
   "config_keys":[("OBSIDIAN_URL","API URL","http://192.168.1.5:27124",False),("OBSIDIAN_API_KEY","API Key","",True)],
   "health_url":lambda: cfg.obsidian_url+"/","health_headers":lambda: {"Authorization":f"Bearer {cfg.obsidian_api_key}"},
   "configured_keys":("obsidian_url","obsidian_api_key"),
   "tools":[{"name":"obsidian_get_daily_note","label":"Today's Daily Note","params":[]},
            {"name":"obsidian_get_note","label":"Get Note","params":[("path","Note path","text")]},
            {"name":"obsidian_write_note","label":"Write Note","params":[("path","Path","text"),("content","Content","text")]},
            {"name":"obsidian_append_to_note","label":"Append to Note","params":[("path","Path","text"),("content","Content","text")]},
            {"name":"obsidian_search","label":"Search Vault","params":[("query","Query","text")]},
            {"name":"obsidian_list_directory","label":"List Directory","params":[("path","Path","text")]}]},

  {"id":"uptime_kuma","label":"Uptime Kuma","icon":"📊","tag":"monitoring","section":"selfhosted",
   "desc":"Self-hosted uptime monitoring",
   "config_keys":[("UPTIME_KUMA_URL","Server URL","http://192.168.1.111:3001",False)],
   "health_url":lambda: cfg.uptime_kuma_url,"health_headers":lambda: {},
   "configured_keys":("uptime_kuma_url",),
   "tools":[{"name":"uptime_status","label":"All Monitors","params":[]}]},

  {"id":"omv","label":"OpenMediaVault","icon":"💾","tag":"system","section":"selfhosted",
   "desc":"NAS management — disks, system info",
   "config_keys":[("OMV_URL","Server URL","http://192.168.1.111",False),("OMV_USERNAME","Username","admin",False),("OMV_PASSWORD","Password","",True)],
   "health_url":lambda: cfg.omv_url+"/api","health_headers":lambda: {},
   "configured_keys":("omv_url","omv_username","omv_password"),
   "tools":[{"name":"omv_system_info","label":"System Info","params":[]},
            {"name":"omv_disk_health","label":"Disk Health & SMART","params":[]}]},

  {"id":"docker","label":"Docker","icon":"🐳","tag":"system","section":"selfhosted",
   "desc":"Container management via socket",
   "config_keys":[("DOCKER_SOCKET","Docker socket path","/var/run/docker.sock",False),("DOCKER_WRITE_ENABLED","Allow write (start/stop/restart)","false",False)],
   "health_url":None,"health_headers":lambda: {},"configured_keys":(),
   "tools":[{"name":"docker_list_containers","label":"List Containers","params":[]},
            {"name":"docker_system_info","label":"System Stats","params":[]},
            {"name":"docker_get_logs","label":"Container Logs","params":[("name_or_id","Container name/ID","text")]},
            {"name":"docker_restart_container","label":"Restart Container","params":[("name_or_id","Container name/ID","text")]},
            {"name":"docker_stop_container","label":"Stop Container","params":[("name_or_id","Container name/ID","text")]},
            {"name":"docker_start_container","label":"Start Container","params":[("name_or_id","Container name/ID","text")]}]},

  # â•â•â•â•â•â•â•â• SYSTEM (built-in) â•â•â•â•â•â•â•â•
  {"id":"filesystem","label":"File Storage & SMB Shares","icon":"📁","tag":"storage","section":"system",
   "desc":"NAS shares and SMB management — read/write files plus mount/list shares",
   "config_keys":[("FILESYSTEM_ALLOWED_PATHS","Allowed local paths (comma-sep)","/01_Offene_Jobs,/Hausatredies,/Ablage,/Backup",False)],
   "health_url":None,"health_headers":lambda: {},"configured_keys":(),
   "tools":[{"name":"smb_list_shares","label":"List Shares","params":[]},
            {"name":"smb_mount_status","label":"Mount Status","params":[]},
            {"name":"smb_browse","label":"Browse Share","params":[("share_name","Share name","text"),("path","Path","text")]},
            {"name":"smb_autodiscover","label":"Autodiscover","params":[("share_name","Share name","text")]},
            {"name":"smb_add_share","label":"Add Share","params":[("name","Name","text"),("server","Server","text"),("share","Share","text"),("mount","Mount point","text")]},
            {"name":"fs_list_shares","label":"All Local Shares","params":[]},
            {"name":"fs_list_directory","label":"List Directory","params":[("path","Path","text")]},
            {"name":"fs_read_file","label":"Read File","params":[("path","File path","text")]},
            {"name":"fs_write_file","label":"Write File","params":[("path","File path","text"),("content","Content","text")]},
            {"name":"fs_search_files","label":"Search Files","params":[("path","In path","text"),("pattern","Pattern","text")]},
            {"name":"fs_recent_files","label":"Recent Files","params":[("path","Path","text"),("days","Days back","number")]}]},

  {"id":"ssh","label":"SSH Client","icon":"🖥️","tag":"network","section":"system",
   "desc":"Multi-host SSH — allowlisted read-only commands + write-enabled hosts",
   "config_keys":[],
   "health_url":None,"health_headers":lambda: {},"configured_keys":(),
   "tools":[{"name":"ssh_list_hosts","label":"List Hosts","params":[]},
            {"name":"ssh_list_commands","label":"Available Commands","params":[]},
            {"name":"ssh_run","label":"Run Command","params":[("host","Host name","text"),("command","Command","text"),("arg","Arg (optional)","text")]},
            {"name":"ssh_test_host","label":"Test Host","params":[("name","Host name","text")]},
            {"name":"ssh_add_host","label":"Add Host","params":[("name","Name","text"),("host","IP/hostname","text"),("user","Username","text"),("readonly","Read-only?","text")]},
            {"name":"ssh_remove_host","label":"Remove Host","params":[("name","Host name","text")]}]},

  {"id":"comfyui","label":"ComfyUI","icon":"🎨","tag":"ai","section":"selfhosted",
   "desc":"Local AI image generation",
   "config_keys":[("COMFYUI_URL","Server URL","http://192.168.1.X:8188",False)],
   "health_url":lambda: cfg.comfyui_url+"/system_stats","health_headers":lambda: {},
   "configured_keys":("comfyui_url",),
   "tools":[{"name":"comfyui_status","label":"Status","params":[]},
            {"name":"comfyui_queue","label":"Queue","params":[]},
            {"name":"comfyui_history","label":"History","params":[]},
            {"name":"comfyui_get_models","label":"Models","params":[]},
            {"name":"comfyui_generate","label":"Generate Image","params":[("positive_prompt","Prompt","text"),("checkpoint","Checkpoint","text"),("width","Width","number"),("height","Height","number")]},
            {"name":"comfyui_interrupt","label":"Cancel","params":[]}]},

  {"id":"comfy_mcp","label":"ComfyUI MCP (comfy-cli)","icon":"🧩","tag":"ai","section":"selfhosted",
   "desc":"Comfy-Org's comfy-mcp, served as comfy_* tools: run workflows and gallery templates, poll and fetch jobs, search the live node and model catalog, validate and vary workflows, manage the install. Targets the ComfyUI card's URL. Ships in the Docker image; elsewhere it is found on PATH or via COMFY_MCP_COMMAND in .env",
   # COMFY_MCP_COMMAND is not editable here on purpose: it names a program to run.
   "config_keys":[("COMFY_API_KEY","Comfy API key (optional — partner-API nodes only)","",True)],
   # No probe: the server is a child process, not an address. comfy_mcp_status
   # starts it and reports what it found.
   "health_url":None,"health_headers":lambda: {},
   "configured_keys":("comfy_mcp_command",),
   "documentation_url":"https://github.com/Comfy-Org/comfy-mcp",
   "tools":[{"name":"comfy_mcp_status","label":"Status & tool guides","params":[("tool","Tool (optional)","text")]}]},

  {"id":"tailscale","label":"Tailscale","icon":"🌐","tag":"network","section":"selfhosted",
   "desc":"VPN mesh network",
   "config_keys":[],"health_url":None,"health_headers":lambda: {},"configured_keys":(),
   "tools":[{"name":"tailscale_status","label":"Network Status","params":[]},
            {"name":"tailscale_ping","label":"Ping Device","params":[("hostname_or_ip","Hostname or IP","text")]}]},

  {"id":"fail2ban","label":"Fail2ban","icon":"🔒","tag":"security","section":"selfhosted",
   "desc":"Intrusion prevention (fail2ban-client on host or docker exec fail2ban)",
   "config_keys":[("FAIL2BAN_WEB_URL","Web UI / docs URL (set to enable)","",False)],
   "open_url_key":"fail2ban_web_url","health_url":None,"health_headers":lambda: {},"configured_keys":("fail2ban_web_url",),
   "tools":[{"name":"fail2ban_status","label":"Jail Status","params":[]},
            {"name":"fail2ban_unban","label":"Unban IP","params":[("ip","IP address","text"),("jail","Jail name","text")]}]},

  {"id":"plutus_router","label":"Plutus Router","icon":"🚦","tag":"system","section":"selfhosted",
   "desc":"Router inspection and MCP exposure reports",
   "config_keys":[],"health_url":None,"health_headers":lambda: {},"configured_keys":(),
   "tools":[{"name":"plutus_tool_slicer","label":"Tool Slicer","params":[("intent","Intent filter","text")]},
            {"name":"test_all_tools","label":"Full Tool Report","params":[]}]},

  # â•â•â•â•â•â•â•â• PUBLIC APIS â•â•â•â•â•â•â•â•
  {"id":"fal","label":"fal.ai","icon":"✨","tag":"ai","section":"public",
   "desc":"Cloud AI — FLUX, WAN, video generation",
   "config_keys":[("FAL_KEY","API Key","",True)],
   "health_url":None,"health_headers":lambda: {},"configured_keys":("fal_key",),
   "tools":[{"name":"fal_generate_image","label":"Generate (FLUX Schnell)","params":[("prompt","Prompt","text"),("model_id","Model ID","text"),("width","Width","number"),("height","Height","number")]},
            {"name":"fal_flux_pro","label":"FLUX Pro","params":[("prompt","Prompt","text"),("aspect_ratio","Aspect ratio","text")]},
            {"name":"fal_list_models_snippet","label":"Available Models","params":[]}]},

  {"id":"weather","label":"Weather (wttr.in)","icon":"🌤","tag":"utilities","section":"public",
   "desc":"Free weather — no key needed, defaults Hamburg",
   "config_keys":[("WEATHER_DEFAULT_LOCATION","Default city","Hamburg",False)],
   "health_url":None,"health_headers":lambda: {},"configured_keys":(),
   "tools":[{"name":"get_context","label":"Date + Time + Weather","params":[]},
            {"name":"weather_current","label":"Current Weather","params":[("location","City","text")]},
            {"name":"weather_forecast","label":"3-Day Forecast","params":[("location","City","text")]}]},

  {"id":"maps","label":"Maps (OpenStreetMap)","icon":"🗺","tag":"utilities","section":"public",
   "desc":"Free routing — no key needed",
   "config_keys":[],"health_url":None,"health_headers":lambda: {},"configured_keys":(),
   "tools":[{"name":"maps_distance","label":"Distance & Travel Time","params":[("origin","From","text"),("destination","To","text"),("mode","Mode","text")]}]},

  {"id":"websearch","label":"Web Search & Fetch","icon":"🔍","tag":"search","section":"public",
   "desc":"DuckDuckGo + page fetch — no key needed",
   "config_keys":[],"health_url":None,"health_headers":lambda: {},"configured_keys":(),
   "tools":[{"name":"web_search","label":"Search Web","params":[("query","Query","text"),("limit","Max","number")]},
            {"name":"web_fetch","label":"Fetch URL","params":[("url","URL","text")]}]},

  {"id":"wikipedia","label":"Wikipedia","icon":"📚","tag":"reference","section":"public",
   "desc":"Article summaries — MediaWiki API, no key",
   "config_keys":[],"health_url":None,"health_headers":lambda: {},"configured_keys":(),
   "tools":[{"name":"wikipedia_summary","label":"Article summary","params":[("title","Article title","text"),("lang","Language code","text")]}]},

  {"id":"currency","label":"Exchange rates","icon":"💱","tag":"finance","section":"public",
   "desc":"Frankfurter (ECB) — no key",
   "config_keys":[],"health_url":None,"health_headers":lambda: {},"configured_keys":(),
   "tools":[{"name":"currency_convert","label":"Convert amount","params":[("amount","Amount","number"),("from_currency","From (ISO)","text"),("to_currency","To (ISO)","text")]},
            {"name":"currency_rates","label":"Latest rates","params":[("base","Base currency","text")]}]},

  {"id":"youtube","label":"YouTube","icon":"▶️","tag":"media","section":"public",
   "desc":"Research any channel or video without a key — transcripts, descriptions, chapters, most-replayed moments, comments, whole-channel stats tables, search rankings, autocomplete keywords, and competitor tracking over time. An API key makes counts exact and adds publish dates",
   "config_keys":[("YOUTUBE_API_KEY","API key (optional — Google Cloud, enable YouTube Data API v3)","",True)],
   # Keyless by design, so the card is never "unconfigured". With a key the probe
   # checks the key itself (a cheap 1-unit call); without one it checks that the
   # public oEmbed endpoint the page-reading tools depend on answers.
   "health_url":lambda: ("https://www.googleapis.com/youtube/v3/i18nLanguages?part=snippet&hl=en"
                         if cfg.youtube_api_key else
                         "https://www.youtube.com/oembed?format=json&url=https://www.youtube.com/watch?v=dQw4w9WgXcQ"),
   "health_headers":lambda: {"X-Goog-Api-Key": cfg.youtube_api_key} if cfg.youtube_api_key else {},
   "configured_keys":(),
   "documentation_url":"https://developers.google.com/youtube/v3/getting-started",
   "tools":[{"name":"youtube_search","label":"Search","params":[("query","Search terms","text"),("max_results","Max results","number"),("order","relevance|date","text")]},
            {"name":"youtube_watch","label":"Watch (full read)","params":[("video","Video ID or URL","text"),("comments","Top comments","number")]},
            {"name":"youtube_transcript","label":"Transcript","params":[("video","Video ID or URL","text"),("lang","Language","text")]},
            {"name":"youtube_video","label":"Video stats","params":[("video_id","Video ID or URL","text")]},
            {"name":"youtube_comments","label":"Comments","params":[("video","Video ID or URL","text"),("max_results","Max","number"),("order","relevance|time","text")]},
            {"name":"youtube_channel","label":"Channel profile","params":[("channel","@handle, ID or URL","text")]},
            {"name":"youtube_channel_videos","label":"Channel uploads table","params":[("channel","@handle, ID or URL","text"),("tab","videos|shorts|streams","text"),("max_results","Max","number"),("sort","recent|views|views_per_day","text")]},
            {"name":"youtube_keywords","label":"Autocomplete keywords","params":[("query","Seed keyword","text"),("source","youtube|google|both","text"),("expand","A–Z long tail","text")]},
            {"name":"youtube_track","label":"Track channels","params":[("action","add|remove|list|snapshot","text"),("channel","@handle","text")]},
            {"name":"youtube_track_report","label":"Tracker report","params":[("channel","Channel (empty = all)","text"),("days","Days","number")]},
            {"name":"youtube_ask_video","label":"Gemini watches it","params":[("video","Video ID or URL","text"),("question","Question","text")]},
            {"name":"youtube_trending","label":"Trending (key)","params":[("region","Region code","text"),("max_results","Max results","number")]}]},

  {"id":"youtube_studio","label":"YouTube Studio & Search Console","icon":"📈","tag":"media","section":"public",
   "desc":"Your own channel's real numbers — watch time, retention, the YouTube search terms that found you, traffic sources, audience, impressions and CTR — plus Google Search Console for your sites. One Google login: add a Desktop-app OAuth client here, then connect under Settings → Google account",
   "config_keys":[("GOOGLE_OAUTH_CLIENT_ID","OAuth client ID (Desktop app type)","…apps.googleusercontent.com",False),
                  ("GOOGLE_OAUTH_CLIENT_SECRET","OAuth client secret","",True),
                  ("GOOGLE_OAUTH_REDIRECT_URI","Redirect URI (optional — only for an https Plutus address)","",False)],
   # No probe: whether the client works is only known once somebody signs in,
   # and Settings → Google account shows exactly that.
   "health_url":None,"health_headers":lambda: {},
   "configured_keys":("google_oauth_client_id","google_oauth_client_secret"),
   "documentation_url":"https://developers.google.com/youtube/analytics",
   "tools":[{"name":"youtube_analytics","label":"Analytics","params":[("report","overview|daily|top_videos|search_terms|traffic_sources|retention|…","text"),("days","Days","number"),("video","Video (optional)","text")]},
            {"name":"youtube_reach","label":"Impressions & CTR","params":[("days","Days","number"),("video","Video (optional)","text")]},
            {"name":"youtube_reach_setup","label":"Set up impressions report","params":[]},
            {"name":"search_console_query","label":"Search Console","params":[("site","Property (empty = list)","text"),("dimension","query|page|country|device|date","text")]}]},

  {"id":"agent_db","label":"Agent Database","icon":"🗄","tag":"storage","section":"system",
   "desc":"Plutus's own SQLite store — the always-writable fallback when Nextcloud, Obsidian or the filesystem are unavailable",
   "config_keys":[],"health_url":None,"health_headers":lambda: {},"configured_keys":(),
   "tools":[{"name":"db_write_note","label":"Save note","params":[("title","Title","text"),("body","Body","text"),("tags","Tags (comma sep)","text")]},
            {"name":"db_read_note","label":"Read note","params":[("note_id","Note id","number")]},
            {"name":"db_list_notes","label":"List notes","params":[("limit","How many","number")]},
            {"name":"db_search_notes","label":"Search notes","params":[("query","Search text","text")]},
            {"name":"db_status","label":"Status","params":[]}]},

  {"id":"reddit","label":"Reddit","icon":"👽","tag":"social","section":"public",
   "desc":"Subreddit posts, search and threads. Add a script app to read as your account — scores, comment counts, your subscriptions, front page and saved posts",
   "config_keys":[("REDDIT_CLIENT_ID","Client ID (script app — reddit.com/prefs/apps)","",False),
                  ("REDDIT_CLIENT_SECRET","Client secret","",True),
                  ("REDDIT_USERNAME","Reddit username","",False),
                  ("REDDIT_PASSWORD","Reddit password","",True)],
   # The .rss feed, not .json: Reddit answers 403 to unauthenticated JSON from
   # every host, so a JSON probe would report the card permanently offline while
   # the tools were working fine.
   "health_url":lambda: "https://www.reddit.com/r/popular/hot.rss?limit=1",
   "health_headers":lambda: {"User-Agent":"PlutusMCP/1.0"},"configured_keys":(),
   "documentation_url":"https://www.reddit.com/dev/api/",
   "tools":[{"name":"reddit_subreddit_posts","label":"Subreddit posts","params":[("subreddit","Subreddit","text"),("sort","hot|new|top|rising","text"),("limit","Max","number")]},
            {"name":"reddit_search","label":"Search","params":[("query","Query","text"),("subreddit","Limit to subreddit","text")]},
            {"name":"reddit_post_comments","label":"Post comments","params":[("permalink","Permalink or URL","text")]},
            {"name":"reddit_me","label":"Who am I (login)","params":[]},
            {"name":"reddit_my_subreddits","label":"My subreddits (login)","params":[("limit","Max","number")]},
            {"name":"reddit_home_feed","label":"My front page (login)","params":[("limit","Max","number")]},
            {"name":"reddit_my_posts","label":"Saved / upvoted (login)","params":[("kind","saved|upvoted|submitted","text"),("limit","Max","number")]},
            {"name":"reddit_submit","label":"Post to a subreddit (login)","params":[("subreddit","Subreddit","text"),("title","Title","text"),("text","Body (text post)","text"),("url","Link (link post)","text"),("account","Account","text")]},
            {"name":"reddit_comment","label":"Reply to a post/comment (login)","params":[("target","Permalink or t3_/t1_ id","text"),("text","Comment","text"),("account","Account","text")]}]},

  {"id":"hackernews","label":"Hacker News","icon":"🟧","tag":"social","section":"public",
   "desc":"Front page and full-history search (Firebase + Algolia, no key)",
   "config_keys":[],"health_url":lambda: "https://hacker-news.firebaseio.com/v0/maxitem.json",
   "health_headers":lambda: {},"configured_keys":(),
   "documentation_url":"https://github.com/HackerNews/API",
   "tools":[{"name":"hackernews_stories","label":"Stories","params":[("feed","top|new|best|ask|show|job","text"),("limit","Max","number")]},
            {"name":"hackernews_search","label":"Search","params":[("query","Query","text"),("sort","relevance|date","text")]}]},

  {"id":"lemmy","label":"Lemmy","icon":"🐭","tag":"social","section":"public",
   "desc":"Fediverse link aggregator — posts from any Lemmy instance, no account",
   "config_keys":[],"health_url":lambda: "https://lemmy.world/api/v3/site",
   "health_headers":lambda: {},"configured_keys":(),
   "documentation_url":"https://join-lemmy.org/api/",
   "tools":[{"name":"lemmy_posts","label":"Posts","params":[("community","Community","text"),("instance","Instance host","text"),("sort","Hot|New|TopDay","text")]}]},

  {"id":"mastodon","label":"Mastodon","icon":"🐘","tag":"social","section":"public",
   "desc":"Public timelines and hashtag feeds from any Mastodon instance (read-only, no account)",
   "config_keys":[],"health_url":lambda: "https://mastodon.social/api/v1/instance",
   "health_headers":lambda: {},"configured_keys":(),
   "documentation_url":"https://docs.joinmastodon.org/api/",
   "tools":[{"name":"mastodon_timeline","label":"Timeline","params":[("tag","Hashtag (blank = public)","text"),("instance","Instance host","text"),("limit","Max","number")]}]},

  {"id":"bluesky","label":"Bluesky","icon":"🦋","tag":"social","section":"public",
   "desc":"Search public Bluesky posts through the public AppView (no account)",
   "config_keys":[],"health_url":lambda: "https://public.api.bsky.app/xrpc/app.bsky.actor.getProfile?actor=bsky.app",
   "health_headers":lambda: {},"configured_keys":(),
   "documentation_url":"https://docs.bsky.app/",
   "tools":[{"name":"bluesky_search","label":"Search posts","params":[("query","Query","text"),("limit","Max","number")]}]},

  {"id":"stackexchange","label":"Stack Exchange","icon":"📚","tag":"social","section":"public",
   "desc":"Stack Overflow and sibling sites — question search on the anonymous quota",
   "config_keys":[],"health_url":lambda: "https://api.stackexchange.com/2.3/info?site=stackoverflow",
   "health_headers":lambda: {},"configured_keys":(),
   "documentation_url":"https://api.stackexchange.com/docs",
   "tools":[{"name":"stackexchange_search","label":"Search questions","params":[("query","Query","text"),("site","Site","text"),("limit","Max","number")]}]},

  {"id":"firecrawl","label":"Firecrawl","icon":"🔥","tag":"search","section":"public",
   "desc":"Reads JavaScript-rendered pages as Markdown — the sites web_fetch comes back empty on. Scrape one page, map a site's URLs, crawl a section, or search the web with results already read",
   "config_keys":[("FIRECRAWL_API_KEY","API key (firecrawl.dev)","",True),
                  ("FIRECRAWL_API_URL","Self-hosted base URL (optional)","",False)],
   "health_url":lambda: f"{(cfg.firecrawl_api_url or 'https://api.firecrawl.dev').rstrip('/')}/v2/scrape",
   "health_headers":lambda: {"Authorization":f"Bearer {cfg.firecrawl_api_key}"} if cfg.firecrawl_api_key else {},
   "configured_keys":("firecrawl_api_key",),
   "documentation_url":"https://docs.firecrawl.dev/api-reference/introduction",
   "tools":[{"name":"firecrawl_scrape","label":"Scrape page","params":[("url","URL","text"),("max_chars","Max chars","number"),("main_content_only","Main content only","text")]},
            {"name":"firecrawl_map","label":"Map site URLs","params":[("url","Site URL","text"),("search","Filter term","text"),("limit","Max","number")]},
            {"name":"firecrawl_crawl","label":"Crawl section","params":[("url","Start URL","text"),("limit","Max pages","number"),("max_depth","Depth","number")]},
            {"name":"firecrawl_search","label":"Search + read","params":[("query","Query","text"),("limit","Max results","number")]}]},

  # The Agent Reach channels (tools/reach.py). Keyless by default — the keys only
  # raise rate limits — so the card is never "unconfigured"; the probe is Jina,
  # the backend the most common read (any web page) depends on.
  {"id":"agent_reach","label":"Agent Reach","icon":"🌐","tag":"search","section":"public",
   "desc":"Agent Reach's internet channels: any page as Markdown (Jina Reader), Exa semantic search, RSS/Atom feeds, Bilibili and V2EX — all keyless — plus reach_doctor, the map of which platform is served by which tool right now",
   "config_keys":[("JINA_API_KEY","Jina Reader key (optional — higher rate limit)","",True),
                  ("EXA_API_KEY","Exa key (optional — without it the keyless MCP endpoint is used)","",True)],
   "health_url":lambda: "https://r.jina.ai/https://example.com",
   "health_headers":lambda: {"User-Agent":"PlutusMCP/1.0"},
   "configured_keys":(),
   "documentation_url":"https://github.com/Panniantong/Agent-Reach",
   "tools":[{"name":"reach_doctor","label":"Doctor (platform map)","params":[("probe","Live check","text")]},
            {"name":"web_read","label":"Read page (Jina)","params":[("url","URL","text"),("max_chars","Max chars","number")]},
            {"name":"exa_search","label":"Exa search","params":[("query","Query","text"),("num_results","Results","number")]},
            {"name":"rss_read","label":"RSS / Atom feed","params":[("url","Feed URL","text"),("limit","Max","number")]},
            {"name":"bilibili_search","label":"Bilibili search","params":[("query","Query (empty = popular)","text"),("limit","Max","number")]},
            {"name":"bilibili_video","label":"Bilibili video","params":[("video","BV id or URL","text"),("comments","Top comments","number")]},
            {"name":"v2ex_topics","label":"V2EX topics","params":[("feed","hot|latest|node","text"),("node","Node","text")]},
            {"name":"v2ex_topic","label":"V2EX topic","params":[("topic","Topic id or URL","text"),("replies","Replies","number")]}]},

  {"id":"twitter","label":"X / Twitter","icon":"𝕏","tag":"social","section":"public",
   "desc":"Search posts, read accounts and threads through twitter-cli (Agent Reach's X backend). X has no keyless read path: paste the auth_token and ct0 cookies of a logged-in x.com session (a spare account is wise). Plutus never reads browser cookies itself",
   "config_keys":[("TWITTER_AUTH_TOKEN","auth_token cookie (x.com)","",True),
                  ("TWITTER_CT0","ct0 cookie (x.com)","",True)],
   # No probe: any request is a read on the account, and reads are rate-limited.
   "health_url":None,"health_headers":lambda: {},
   "configured_keys":("twitter_auth_token","twitter_ct0"),
   "documentation_url":"https://github.com/jackwener/twitter-cli",
   "tools":[{"name":"twitter_search","label":"Search posts","params":[("query","Query","text"),("tab","Top|Latest","text"),("limit","Max","number")]},
            {"name":"twitter_user_posts","label":"Account + posts","params":[("user","@handle","text"),("limit","Posts","number")]},
            {"name":"twitter_tweet","label":"Post + replies","params":[("tweet","Tweet URL or id","text"),("replies","Replies","number")]}]},

  {"id":"google_trends","label":"Google Trends","icon":"📈","tag":"search","section":"public",
   "desc":"Compare interest in up to five terms over time — Google web search or YouTube search only — as Google's 0–100 relative index, with top and rising related searches. Free, no key",
   "config_keys":[],"health_url":None,"health_headers":lambda: {},"configured_keys":(),
   "documentation_url":"https://support.google.com/trends/answer/4365533",
   "tools":[{"name":"trends_compare","label":"Compare interest","params":[("keywords","Terms (comma sep, ≤5)","text"),("search_type","web|youtube|images|news","text"),("timeframe","7d|1m|3m|12m|5y|all","text"),("country","Country (DE, US…)","text")]}]},

  {"id":"keyword_volume","label":"Keyword volume","icon":"📊","tag":"search","section":"public",
   "desc":"How many people search Google for a phrase — Keyword Planner's average monthly searches, the monthly trend, competition and bid range, plus related ideas. Google Ads API (developer token with Basic access + the Google login) or DataForSEO (pay per request)",
   "config_keys":[("GOOGLE_ADS_DEVELOPER_TOKEN","Google Ads developer token (Basic access)","",True),
                  ("GOOGLE_ADS_CUSTOMER_ID","Google Ads account id","123-456-7890",False),
                  ("GOOGLE_ADS_LOGIN_CUSTOMER_ID","Manager account id (if reached through one)","",False),
                  ("DATAFORSEO_LOGIN","DataForSEO login (alternative)","",False),
                  ("DATAFORSEO_PASSWORD","DataForSEO API password","",True)],
   "health_url":None,"health_headers":lambda: {},
   "configured_keys":(),
   "documentation_url":"https://developers.google.com/google-ads/api/docs/keyword-planning/generate-keyword-ideas",
   "tools":[{"name":"keyword_volume","label":"Search volume","params":[("keywords","Keywords (comma sep)","text"),("country","Country (DE, US…)","text"),("language","Language","text"),("ideas","Related ideas","text")]}]},

  {"id":"github","label":"GitHub","icon":"🐙","tag":"dev","section":"public",
   "desc":"GitHub — public research without a token; with one, your account's own client: private repos, code search, Actions, and commits, issues, PRs and comments as you",
   "config_keys":[("GITHUB_TOKEN","Access token — `repo` scope to write; omit for public read-only","",True)],
   "health_url":lambda: "https://api.github.com/rate_limit","health_headers":lambda: {},
   "configured_keys":(),
   "documentation_url":"https://docs.github.com/en/rest",
   "tools":[{"name":"github_search_repos","label":"Search Repos","params":[("query","Search terms","text"),("sort","stars|forks|updated","text"),("limit","Max results","number")]},
            {"name":"github_repo_info","label":"Repo Info","params":[("repo","owner/repo","text")]},
            {"name":"github_list_issues","label":"List Issues","params":[("repo","owner/repo","text"),("state","open|closed|all","text")]},
            {"name":"github_list_pulls","label":"List PRs","params":[("repo","owner/repo","text"),("state","open|closed|all","text")]},
            {"name":"github_me","label":"Who am I (token)","params":[]},
            {"name":"github_my_repos","label":"My repos (token)","params":[("visibility","all|public|private","text"),("limit","Max","number")]},
            {"name":"github_read_file","label":"Read file","params":[("repo","owner/repo","text"),("path","Path in repo","text"),("ref","Branch/tag","text")]},
            {"name":"github_list_branches","label":"Branches","params":[("repo","owner/repo","text")]},
            {"name":"github_list_commits","label":"Commits","params":[("repo","owner/repo","text"),("branch","Branch","text"),("path","Path filter","text")]},
            {"name":"github_search_code","label":"Search code (token)","params":[("query","Code query","text"),("limit","Max","number")]},
            {"name":"github_workflow_runs","label":"Actions runs","params":[("repo","owner/repo","text"),("branch","Branch","text")]},
            {"name":"github_notifications","label":"Notifications (token)","params":[("limit","Max","number")]},
            {"name":"github_write_file","label":"Commit a file (token)","params":[("repo","owner/repo","text"),("path","Path","text"),("content","Contents","text"),("message","Commit message","text"),("branch","Branch","text")]},
            {"name":"github_create_issue","label":"Open issue (token)","params":[("repo","owner/repo","text"),("title","Title","text"),("body","Body","text"),("labels","Labels (comma)","text")]},
            {"name":"github_comment","label":"Comment (token)","params":[("repo","owner/repo","text"),("number","Issue/PR number","number"),("body","Comment","text")]},
            {"name":"github_set_issue_state","label":"Close/reopen issue (token)","params":[("repo","owner/repo","text"),("number","Issue number","number"),("state","closed|open","text")]},
            {"name":"github_create_branch","label":"Create branch (token)","params":[("repo","owner/repo","text"),("name","New branch","text"),("base","From branch","text")]},
            {"name":"github_create_repo","label":"Create repo (token)","params":[("name","Repository name","text"),("description","Description","text"),("private","Private (true/false)","text"),("org","Organisation (optional)","text")]},
            {"name":"github_create_pull","label":"Open pull request (token)","params":[("repo","owner/repo","text"),("title","Title","text"),("head","From branch","text"),("base","Into branch","text"),("body","Description","text")]}]},

  {"id":"gitlab","label":"GitLab","icon":"🦊","tag":"dev","section":"public",
   "desc":"GitLab — project search, project info, issues & merge requests (gitlab.com or self-hosted)",
   "config_keys":[("GITLAB_URL","Instance URL","https://gitlab.com",False),("GITLAB_TOKEN","Access token (optional — private + higher limits)","",True)],
   "health_url":lambda: (cfg.gitlab_url or "https://gitlab.com").rstrip("/")+"/api/v4/version","health_headers":lambda: {},
   "configured_keys":(),
   "documentation_url":"https://docs.gitlab.com/ee/api/",
   "tools":[{"name":"gitlab_search_projects","label":"Search Projects","params":[("query","Search terms","text"),("limit","Max results","number")]},
            {"name":"gitlab_project_info","label":"Project Info","params":[("project","namespace/project or ID","text")]},
            {"name":"gitlab_list_issues","label":"List Issues","params":[("project","namespace/project or ID","text"),("state","opened|closed|all","text")]},
            {"name":"gitlab_list_merge_requests","label":"List MRs","params":[("project","namespace/project or ID","text"),("state","opened|closed|all","text")]}]},

  {"id":"huggingface","label":"Hugging Face","icon":"🤗","tag":"ai","section":"public",
   "desc":"Hugging Face Hub — model discovery, trending models, metadata (public API, no key needed)",
   "config_keys":[("HF_TOKEN","Access token (optional — higher rate limits / private repos)","",True)],
   "health_url":lambda: "https://huggingface.co/api/models?limit=1","health_headers":lambda: {},
   "configured_keys":(),
   "documentation_url":"https://huggingface.co/docs/hub/api",
   "tools":[{"name":"huggingface_search_models","label":"Search Models","params":[("query","Search terms","text"),("sort","downloads|likes|trending","text"),("limit","Max results","number")]},
            {"name":"huggingface_trending_models","label":"Trending Models","params":[("task","Task filter (optional)","text"),("limit","Max results","number")]},
            {"name":"huggingface_model_info","label":"Model Info","params":[("model_id","org/model","text")]}]},

  {"id":"google","label":"Google Custom Search","icon":"🔎","tag":"search","section":"public",
   "desc":"Programmable Search JSON API — set GOOGLE_API_KEY + GOOGLE_CSE_ID",
   "config_keys":[("GOOGLE_API_KEY","Google Cloud API key","",True),("GOOGLE_CSE_ID","Search engine ID (cx)","",False)],
   "health_url":None,"health_headers":lambda: {},"configured_keys":("google_api_key","google_cse_id"),
   "tools":[{"name":"google_search","label":"Google web search","params":[("query","Query","text"),("num","Max results","number")]}]},

  {"id":"smtp","label":"Email / Proton Bridge","icon":"📧","tag":"communication","section":"public",
   "desc":"Send via Proton Bridge SMTP or any SMTP",
   "config_keys":[("SMTP_HOST","SMTP Host","127.0.0.1",False),("SMTP_PORT","Port","1025",False),("SMTP_USERNAME","From address","",False),("SMTP_PASSWORD","Password","",True)],
   "health_url":None,"health_headers":lambda: {},"configured_keys":("smtp_host","smtp_username"),
   "tools":[{"name":"send_email","label":"Send Email","params":[("to","Recipient","text"),("subject","Subject","text"),("body","Body","text")]},
            {"name":"proton_bridge_status","label":"Bridge Status & Guide","params":[]}]},
]


OPEN_URL_BY_ID: dict[str, str] = {
    "jellyfin": "jellyfin_url",
    "sonarr": "sonarr_url",
    "radarr": "radarr_url",
    "lidarr": "lidarr_url",
    "jellyseerr": "jellyseerr_url",
    "qbittorrent": "qbittorrent_url",
    "immich": "immich_url",
    "homeassistant": "ha_url",
    "nextcloud": "nextcloud_url",
    "habitica": "habitica_url",
    "n8n": "n8n_url",
    "ntfy": "ntfy_url",
    "syncthing": "syncthing_url",
    "obsidian": "obsidian_url",
    "uptime_kuma": "uptime_kuma_url",
    "omv": "omv_url",
    "comfyui": "comfyui_url",
}


# ── Brand-logo metadata (single source of truth) ──────────────────────────────
# Canonical here, alongside the service catalogue, so a service is defined in one
# module. These used to live in core/service_logos.py as two hand-maintained
# dicts that had drifted — "fal"/"weather"/"currency" appeared twice, and the
# duplicate "currency" key silently flipped the domain from frankfurter.app to
# ecb.europa.eu. service_logos.py is now pure rendering and imports these.
#
# Ids split into two groups: those that are entries in SERVICES above, and the
# dashboard-bookmark / public-API-aggregate ids that are not (they have no
# SERVICES row but still render a card and need a mark).
SERVICE_LOGO_DOMAIN: dict[str, str] = {
    # — services in the catalogue —
    "jellyfin": "jellyfin.org", "sonarr": "sonarr.tv", "radarr": "radarr.video",
    "lidarr": "lidarr.audio", "jellyseerr": "jellyfin.org", "qbittorrent": "qbittorrent.org",
    "immich": "immich.app", "homeassistant": "home-assistant.io", "nextcloud": "nextcloud.com",
    "habitica": "habitica.com", "n8n": "n8n.io", "ntfy": "ntfy.sh", "syncthing": "syncthing.net",
    "obsidian": "obsidian.md", "uptime_kuma": "uptime-kuma.io", "omv": "openmediavault.org",
    "docker": "docker.com", "comfyui": "github.com", "comfy_mcp": "comfy.org", "tailscale": "tailscale.com",
    "fail2ban": "fail2ban.org", "fal": "fal.ai", "weather": "wttr.in", "maps": "openstreetmap.org",
    "websearch": "duckduckgo.com", "smtp": "proton.me", "wikipedia": "wikipedia.org",
    # ECB, not frankfurter.app: this is the value that already won before the
    # duplicate keys were removed, kept for parity.
    "currency": "ecb.europa.eu", "google": "google.com",
    "github": "github.com", "gitlab": "gitlab.com", "huggingface": "huggingface.co",
    "youtube": "youtube.com", "youtube_studio": "studio.youtube.com",
    "agent_reach": "jina.ai", "twitter": "x.com", "keyword_volume": "ads.google.com", "google_trends": "trends.google.com",
    # — dashboard bookmarks / public aggregates (no SERVICES row) —
    "pub_network": "httpbin.org", "pub_geo_time": "openstreetmap.org",
    "pub_finance_crypto": "coingecko.com", "pub_fun": "quotable.io",
    "pub_education": "openlibrary.org", "pub_games": "pokeapi.co", "pub_space": "nasa.gov",
    "pub_dev_culture": "github.com",
    "audiobookshelf": "audiobookshelf.org", "kavita": "kavitareader.com",
    "paperless": "docs.paperless-ngx.com", "vaultwarden": "vaultwarden.org",
    "portainer": "portainer.io", "gitea": "gitea.io", "grafana": "grafana.com",
    "prometheus": "prometheus.io", "pihole": "pi-hole.net", "adguard": "adguard.com",
    "transmission": "transmissionbt.com", "sabnzbd": "sabnzbd.org", "bookstack": "bookstackapp.com",
    "minio": "min.io", "matrix_synapse": "matrix.org", "ghost": "ghost.org", "wikijs": "js.wiki",
}

SERVICE_ICON_SLUG: dict[str, str] = {
    "docker": "docker", "jellyfin": "jellyfin", "sonarr": "sonarr", "radarr": "radarr",
    "lidarr": "lidarr", "immich": "immich", "homeassistant": "homeassistant",
    "nextcloud": "nextcloud", "n8n": "n8n", "syncthing": "syncthing", "tailscale": "tailscale",
    "qbittorrent": "qbittorrent", "obsidian": "obsidian", "postgres": "postgresql",
    "comfyui": "comfyui", "comfy_mcp": "comfyui", "ntfy": "ntfy", "maps": "openstreetmap", "websearch": "duckduckgo",
    "wikipedia": "wikipedia", "google": "google", "currency": "eurostat",
    "github": "github", "gitlab": "gitlab", "huggingface": "huggingface", "youtube": "youtube",
    "youtube_studio": "youtube", "twitter": "x", "keyword_volume": "googleads", "google_trends": "google",
    "pub_network": "cloudflare", "pub_geo_time": "openstreetmap", "pub_finance_crypto": "coingecko",
    "pub_fun": "steam", "pub_education": "wikimediafoundation", "pub_games": "nintendo",
    "pub_space": "nasa", "pub_dev_culture": "github",
    "audiobookshelf": "audiobookshelf", "vaultwarden": "bitwarden", "portainer": "portainer",
    "gitea": "gitea", "grafana": "grafana", "prometheus": "prometheus", "pihole": "pi-hole",
    "minio": "minio", "ghost": "ghost",
}

