"""Canonical built-in service and capability metadata."""

from __future__ import annotations

from config import cfg

SERVICES: list[dict] = [
  # â•â•â•â•â•â•â•â• SELF-HOSTED â•â•â•â•â•â•â•â•
  {"id":"jellyfin","label":"Jellyfin","icon":"🎬","tag":"media","section":"selfhosted",
   "desc":"Media server — movies, TV, music",
   "config_keys":[("JELLYFIN_URL","Server URL","http://192.168.1.111:8096",False),("JELLYFIN_API_KEY","API Key","",True),("JELLYFIN_USER_ID","User ID","",False)],
   "health_url":lambda: cfg.jellyfin_url+"/health","health_headers":lambda: {"X-Emby-Token":cfg.jellyfin_api_key},
   "configured_keys":("jellyfin_url","jellyfin_api_key"),
   "tools":[{"name":"jellyfin_search","label":"Search Library","params":[("query","Search term","text"),("limit","Max results","number")]},
            {"name":"jellyfin_recently_added","label":"Recently Added","params":[("limit","Max results","number")]}]},

  {"id":"sonarr","label":"Sonarr","icon":"📺","tag":"arr","section":"selfhosted",
   "desc":"TV show management & downloading",
   "config_keys":[("SONARR_URL","Server URL","http://192.168.1.111:8989",False),("SONARR_API_KEY","API Key","",True)],
   "health_url":lambda: cfg.sonarr_url+"/api/v3/health","health_headers":lambda: {"X-Api-Key":cfg.sonarr_api_key},
   "configured_keys":("sonarr_url","sonarr_api_key"),
   "tools":[{"name":"sonarr_search_show","label":"Search Show","params":[("query","Show name","text")]},
            {"name":"sonarr_list_series","label":"All Series","params":[]},
            {"name":"sonarr_add_series","label":"Add Series","params":[("tvdb_id","TVDB ID","number"),("title","Title","text")]},
            {"name":"sonarr_queue","label":"Queue","params":[]},
            {"name":"sonarr_calendar","label":"Upcoming (7d)","params":[]},
            {"name":"sonarr_missing","label":"Missing Episodes","params":[]}]},

  {"id":"radarr","label":"Radarr","icon":"🎥","tag":"arr","section":"selfhosted",
   "desc":"Movie management & downloading",
   "config_keys":[("RADARR_URL","Server URL","http://192.168.1.111:7878",False),("RADARR_API_KEY","API Key","",True)],
   "health_url":lambda: cfg.radarr_url+"/api/v3/health","health_headers":lambda: {"X-Api-Key":cfg.radarr_api_key},
   "configured_keys":("radarr_url","radarr_api_key"),
   "tools":[{"name":"radarr_search_movie","label":"Search Movie","params":[("query","Movie name","text")]},
            {"name":"radarr_list_movies","label":"All Movies","params":[]},
            {"name":"radarr_add_movie","label":"Add Movie","params":[("tmdb_id","TMDB ID","number"),("title","Title","text")]},
            {"name":"radarr_queue","label":"Queue","params":[]}]},

  {"id":"lidarr","label":"Lidarr","icon":"🎵","tag":"arr","section":"selfhosted",
   "desc":"Music management & downloading",
   "config_keys":[("LIDARR_URL","Server URL","http://192.168.1.111:8686",False),("LIDARR_API_KEY","API Key","",True)],
   "health_url":lambda: cfg.lidarr_url+"/api/v3/health","health_headers":lambda: {"X-Api-Key":cfg.lidarr_api_key},
   "configured_keys":("lidarr_url","lidarr_api_key"),
   "tools":[{"name":"lidarr_search_artist","label":"Search Artist","params":[("query","Artist name","text")]},
            {"name":"lidarr_list_artists","label":"All Artists","params":[]},
            {"name":"lidarr_queue","label":"Queue","params":[]}]},

  {"id":"jellyseerr","label":"Jellyseerr","icon":"📋","tag":"media","section":"selfhosted",
   "desc":"Content request management",
   "config_keys":[("JELLYSEERR_URL","Server URL","http://192.168.1.111:5055",False),("JELLYSEERR_API_KEY","API Key","",True)],
   "health_url":lambda: cfg.jellyseerr_url+"/api/v1/status","health_headers":lambda: {"X-Api-Key":cfg.jellyseerr_api_key},
   "configured_keys":("jellyseerr_url","jellyseerr_api_key"),
   "tools":[{"name":"jellyseerr_request","label":"Request Content","params":[("media_type","Type","text"),("media_id","ID","number")]},
            {"name":"jellyseerr_requests","label":"All Requests","params":[]}]},

  {"id":"qbittorrent","label":"qBittorrent","icon":"⬇️","tag":"media","section":"selfhosted",
   "desc":"Torrent download client",
   "config_keys":[("QBITTORRENT_URL","Server URL","http://192.168.1.111:8080",False),("QBITTORRENT_USERNAME","Username","admin",False),("QBITTORRENT_PASSWORD","Password","",True)],
   "health_url":lambda: cfg.qbittorrent_url+"/api/v2/app/version","health_headers":lambda: {},
   "configured_keys":("qbittorrent_url","qbittorrent_password"),
   "tools":[{"name":"qbittorrent_list","label":"Active Downloads","params":[]},
            {"name":"qbittorrent_pause","label":"Pause","params":[("hash","Torrent hash","text")]},
            {"name":"qbittorrent_resume","label":"Resume","params":[("hash","Torrent hash","text")]},
            {"name":"qbittorrent_delete","label":"Delete","params":[("hash","Torrent hash","text")]}]},

  {"id":"immich","label":"Immich","icon":"📸","tag":"photos","section":"selfhosted",
   "desc":"Self-hosted photo & video library",
   "config_keys":[("IMMICH_URL","Server URL","http://192.168.1.111:2283",False),("IMMICH_API_KEY","API Key","",True)],
   "health_url":lambda: cfg.immich_url+"/api/server/ping","health_headers":lambda: {"x-api-key":cfg.immich_api_key},
   "configured_keys":("immich_url","immich_api_key"),
   "tools":[{"name":"immich_search","label":"Smart Search","params":[("query","Query","text")]},
            {"name":"immich_list_albums","label":"Albums","params":[]},
            {"name":"immich_get_memories","label":"Today Memories","params":[]},
            {"name":"immich_list_people","label":"People","params":[]},
            {"name":"immich_search_by_metadata","label":"Search by Date/City","params":[("year","Year","number"),("city","City","text")]}]},

  {"id":"homeassistant","label":"Home Assistant","icon":"🏠","tag":"home","section":"selfhosted",
   "desc":"Home automation platform",
   "config_keys":[("HA_URL","Server URL","http://192.168.1.X:8123",False),("HA_TOKEN","Long-Lived Token","",True)],
   "health_url":lambda: cfg.ha_url+"/api/","health_headers":lambda: {"Authorization":f"Bearer {cfg.ha_token}"},
   "configured_keys":("ha_url","ha_token"),
   "tools":[{"name":"ha_get_states","label":"All States","params":[]},
            {"name":"ha_search_entities","label":"Search Entities","params":[("query","Search","text")]},
            {"name":"ha_turn_on","label":"Turn On","params":[("entity_id","Entity ID","text")]},
            {"name":"ha_turn_off","label":"Turn Off","params":[("entity_id","Entity ID","text")]},
            {"name":"ha_call_service","label":"Call Service","params":[("domain","Domain","text"),("service","Service","text"),("entity_id","Entity ID","text")]}]},

  {"id":"nextcloud","label":"Nextcloud","icon":"☁️","tag":"cloud","section":"selfhosted",
   "desc":"Files, calendar, contacts, notes",
   "config_keys":[("NEXTCLOUD_URL","Server URL","http://192.168.1.111/nextcloud",False),("NEXTCLOUD_USERNAME","Username","",False),("NEXTCLOUD_PASSWORD","Password / App Token","",True)],
   "health_url":lambda: cfg.nextcloud_url+"/status.php","health_headers":lambda: {},
   "configured_keys":("nextcloud_url","nextcloud_username","nextcloud_password"),
   "tools":[{"name":"nextcloud_list_calendars","label":"Calendars","params":[]},
            {"name":"nextcloud_get_events","label":"Get Events","params":[("calendar","Calendar slug","text"),("days_ahead","Days ahead","number")]},
            {"name":"nextcloud_add_event","label":"Add Event","params":[("calendar","Slug","text"),("title","Title","text"),("date","YYYY-MM-DD","text"),("start_time","HH:MM","text")]},
            {"name":"nextcloud_get_tasks","label":"Tasks","params":[("list_name","List slug","text")]},
            {"name":"nextcloud_add_task","label":"Add Task","params":[("title","Title","text"),("due_date","Due date","text")]},
            {"name":"nextcloud_list_contacts","label":"Contacts","params":[]},
            {"name":"nextcloud_search_contacts","label":"Search Contacts","params":[("query","Name/email","text")]},
            {"name":"nextcloud_add_contact","label":"Add Contact","params":[("name","Full name","text"),("email","Email","text")]},
            {"name":"nextcloud_list_files","label":"Files","params":[("path","Folder path","text")]},
            {"name":"nextcloud_get_notes","label":"Notes","params":[]},
            {"name":"nextcloud_create_note","label":"Create Note","params":[("title","Title","text"),("content","Content","text")]},
            {"name":"nextcloud_get_user_info","label":"User Info","params":[]},
            {"name":"nextcloud_get_activity","label":"Activity","params":[]},
            {"name":"nextcloud_list_shares","label":"Shares","params":[]}]},

  {"id":"habitica","label":"Habitica","icon":"🎮","tag":"personal","section":"selfhosted",
   "desc":"Habit & task RPG (self-hosted)",
   "config_keys":[("HABITICA_URL","Server URL","http://192.168.1.111:3030",False),("HABITICA_USER_ID","User ID","",False),("HABITICA_API_TOKEN","API Token","",True)],
   "health_url":lambda: cfg.habitica_url+"/api/v4/status","health_headers":lambda: {},
   "configured_keys":("habitica_url","habitica_user_id","habitica_api_token"),
   "tools":[{"name":"habitica_get_stats","label":"Character Stats","params":[]},
            {"name":"habitica_get_tasks","label":"All Tasks","params":[]},
            {"name":"habitica_score_task","label":"Score Task","params":[("task_id","Task ID","text")]},
            {"name":"habitica_add_todo","label":"Add To-Do","params":[("text","Task name","text")]},
            {"name":"habitica_add_habit","label":"Add Habit","params":[("text","Habit name","text")]}]},

  {"id":"n8n","label":"n8n","icon":"⚡","tag":"automation","section":"selfhosted",
   "desc":"Workflow automation",
   "config_keys":[("N8N_URL","Server URL","http://192.168.1.111:5678",False),("N8N_API_KEY","API Key","",True)],
   "health_url":lambda: cfg.n8n_url+"/healthz","health_headers":lambda: {},
   "configured_keys":("n8n_url","n8n_api_key"),
   "tools":[{"name":"n8n_list_workflows","label":"All Workflows","params":[]},
            {"name":"n8n_get_executions","label":"Recent Executions","params":[]},
            {"name":"n8n_trigger_webhook","label":"Trigger Webhook","params":[("webhook_path","Path","text")]}]},

  {"id":"ntfy","label":"Ntfy","icon":"🔔","tag":"notifications","section":"selfhosted",
   "desc":"Push notification server",
   "config_keys":[("NTFY_URL","Server URL","http://192.168.1.111:5050",False),("NTFY_USERNAME","Username (required to mark configured)","",False),("NTFY_PASSWORD","Password / token","",True),("NTFY_DEFAULT_TOPIC","Default Topic","assistant",False)],
   "health_url":lambda: cfg.ntfy_url+"/v1/health","health_headers":lambda: ({"Authorization": f"Basic {__import__('base64').b64encode((cfg.ntfy_username + ':' + cfg.ntfy_password).encode()).decode()}"} if cfg.ntfy_username else {}),
   "configured_keys":("ntfy_url","ntfy_username"),
   "tools":[{"name":"ntfy_send","label":"Send Notification","params":[("message","Message","text"),("topic","Topic","text"),("title","Title","text")]}]},

  {"id":"syncthing","label":"Syncthing","icon":"🔄","tag":"sync","section":"selfhosted",
   "desc":"Continuous file sync",
   "config_keys":[("SYNCTHING_URL","Server URL","http://192.168.1.111:8384",False),("SYNCTHING_API_KEY","API Key","",True)],
   "health_url":lambda: cfg.syncthing_url+"/rest/system/ping","health_headers":lambda: {"X-API-Key":cfg.syncthing_api_key},
   "configured_keys":("syncthing_url","syncthing_api_key"),
   "tools":[{"name":"syncthing_status","label":"Status","params":[]},
            {"name":"syncthing_folders","label":"Folders","params":[]},
            {"name":"syncthing_devices","label":"Devices","params":[]},
            {"name":"syncthing_rescan","label":"Rescan Folder","params":[("folder_id","Folder ID","text")]}]},

  {"id":"obsidian","label":"Obsidian","icon":"📝","tag":"notes","section":"selfhosted",
   "desc":"Local REST API plugin",
   "config_keys":[("OBSIDIAN_URL","API URL","http://192.168.1.5:27124",False),("OBSIDIAN_API_KEY","API Key","",True)],
   "health_url":lambda: cfg.obsidian_url+"/","health_headers":lambda: {"Authorization":f"Bearer {cfg.obsidian_api_key}"},
   "configured_keys":("obsidian_url","obsidian_api_key"),
   "tools":[{"name":"obsidian_get_daily_note","label":"Today's Daily Note","params":[]},
            {"name":"obsidian_get_note","label":"Get Note","params":[("path","Note path","text")]},
            {"name":"obsidian_write_note","label":"Write Note","params":[("path","Path","text"),("content","Content","text")]},
            {"name":"obsidian_append_to_note","label":"Append to Note","params":[("path","Path","text"),("content","Content","text")]},
            {"name":"obsidian_search","label":"Search Vault","params":[("query","Query","text")]},
            {"name":"obsidian_list_directory","label":"List Directory","params":[("path","Path","text")]}]},

  {"id":"uptime_kuma","label":"Uptime Kuma","icon":"📊","tag":"monitoring","section":"selfhosted",
   "desc":"Self-hosted uptime monitoring",
   "config_keys":[("UPTIME_KUMA_URL","Server URL","http://192.168.1.111:3001",False)],
   "health_url":lambda: cfg.uptime_kuma_url,"health_headers":lambda: {},
   "configured_keys":("uptime_kuma_url",),
   "tools":[{"name":"uptime_status","label":"All Monitors","params":[]}]},

  {"id":"omv","label":"OpenMediaVault","icon":"💾","tag":"system","section":"selfhosted",
   "desc":"NAS management — disks, system info",
   "config_keys":[("OMV_URL","Server URL","http://192.168.1.111",False),("OMV_USERNAME","Username","admin",False),("OMV_PASSWORD","Password","",True)],
   "health_url":lambda: cfg.omv_url+"/api","health_headers":lambda: {},
   "configured_keys":("omv_url","omv_username","omv_password"),
   "tools":[{"name":"omv_system_info","label":"System Info","params":[]},
            {"name":"omv_disk_health","label":"Disk Health & SMART","params":[]}]},

  {"id":"docker","label":"Docker","icon":"🐳","tag":"system","section":"selfhosted",
   "desc":"Container management via socket",
   "config_keys":[("DOCKER_WRITE_ENABLED","Allow write (start/stop/restart)","false",False)],
   "health_url":None,"health_headers":lambda: {},"configured_keys":(),
   "tools":[{"name":"docker_list_containers","label":"List Containers","params":[]},
            {"name":"docker_system_info","label":"System Stats","params":[]},
            {"name":"docker_get_logs","label":"Container Logs","params":[("name_or_id","Container name/ID","text")]},
            {"name":"docker_restart_container","label":"Restart Container","params":[("name_or_id","Container name/ID","text")]},
            {"name":"docker_stop_container","label":"Stop Container","params":[("name_or_id","Container name/ID","text")]},
            {"name":"docker_start_container","label":"Start Container","params":[("name_or_id","Container name/ID","text")]}]},

  # â•â•â•â•â•â•â•â• SYSTEM (built-in) â•â•â•â•â•â•â•â•
  {"id":"filesystem","label":"File Storage & SMB Shares","icon":"📁","tag":"storage","section":"system",
   "desc":"NAS shares and SMB management — read/write files plus mount/list shares",
   "config_keys":[("FILESYSTEM_ALLOWED_PATHS","Allowed local paths (comma-sep)","/01_Offene_Jobs,/Hausatredies,/Ablage,/Backup",False)],
   "health_url":None,"health_headers":lambda: {},"configured_keys":(),
   "tools":[{"name":"smb_list_shares","label":"List Shares","params":[]},
            {"name":"smb_mount_status","label":"Mount Status","params":[]},
            {"name":"smb_browse","label":"Browse Share","params":[("share_name","Share name","text"),("path","Path","text")]},
            {"name":"smb_autodiscover","label":"Autodiscover","params":[("share_name","Share name","text")]},
            {"name":"smb_add_share","label":"Add Share","params":[("name","Name","text"),("server","Server","text"),("share","Share","text"),("mount","Mount point","text")]},
            {"name":"fs_list_shares","label":"All Local Shares","params":[]},
            {"name":"fs_list_directory","label":"List Directory","params":[("path","Path","text")]},
            {"name":"fs_read_file","label":"Read File","params":[("path","File path","text")]},
            {"name":"fs_write_file","label":"Write File","params":[("path","File path","text"),("content","Content","text")]},
            {"name":"fs_search_files","label":"Search Files","params":[("path","In path","text"),("pattern","Pattern","text")]},
            {"name":"fs_recent_files","label":"Recent Files","params":[("path","Path","text"),("days","Days back","number")]}]},

  {"id":"ssh","label":"SSH Client","icon":"🖥️","tag":"network","section":"system",
   "desc":"Multi-host SSH — allowlisted read-only commands + write-enabled hosts",
   "config_keys":[],
   "health_url":None,"health_headers":lambda: {},"configured_keys":(),
   "tools":[{"name":"ssh_list_hosts","label":"List Hosts","params":[]},
            {"name":"ssh_list_commands","label":"Available Commands","params":[]},
            {"name":"ssh_run","label":"Run Command","params":[("host","Host name","text"),("command","Command","text"),("arg","Arg (optional)","text")]},
            {"name":"ssh_test_host","label":"Test Host","params":[("name","Host name","text")]},
            {"name":"ssh_add_host","label":"Add Host","params":[("name","Name","text"),("host","IP/hostname","text"),("user","Username","text"),("readonly","Read-only?","text")]},
            {"name":"ssh_remove_host","label":"Remove Host","params":[("name","Host name","text")]}]},

  {"id":"comfyui","label":"ComfyUI","icon":"🎨","tag":"ai","section":"selfhosted",
   "desc":"Local AI image generation",
   "config_keys":[("COMFYUI_URL","Server URL","http://192.168.1.X:8188",False)],
   "health_url":lambda: cfg.comfyui_url+"/system_stats","health_headers":lambda: {},
   "configured_keys":("comfyui_url",),
   "tools":[{"name":"comfyui_status","label":"Status","params":[]},
            {"name":"comfyui_queue","label":"Queue","params":[]},
            {"name":"comfyui_history","label":"History","params":[]},
            {"name":"comfyui_get_models","label":"Models","params":[]},
            {"name":"comfyui_generate","label":"Generate Image","params":[("positive_prompt","Prompt","text"),("checkpoint","Checkpoint","text"),("width","Width","number"),("height","Height","number")]},
            {"name":"comfyui_interrupt","label":"Cancel","params":[]}]},

  {"id":"tailscale","label":"Tailscale","icon":"🌐","tag":"network","section":"selfhosted",
   "desc":"VPN mesh network",
   "config_keys":[],"health_url":None,"health_headers":lambda: {},"configured_keys":(),
   "tools":[{"name":"tailscale_status","label":"Network Status","params":[]},
            {"name":"tailscale_ping","label":"Ping Device","params":[("hostname_or_ip","Hostname or IP","text")]}]},

  {"id":"fail2ban","label":"Fail2ban","icon":"🔒","tag":"security","section":"selfhosted",
   "desc":"Intrusion prevention (fail2ban-client on host or docker exec fail2ban)",
   "config_keys":[("FAIL2BAN_WEB_URL","Web UI / docs URL (set to enable)","",False)],
   "open_url_key":"fail2ban_web_url","health_url":None,"health_headers":lambda: {},"configured_keys":("fail2ban_web_url",),
   "tools":[{"name":"fail2ban_status","label":"Jail Status","params":[]},
            {"name":"fail2ban_unban","label":"Unban IP","params":[("ip","IP address","text"),("jail","Jail name","text")]}]},

  {"id":"plutus_router","label":"Plutus Router","icon":"🚦","tag":"system","section":"selfhosted",
   "desc":"Router inspection and MCP exposure reports",
   "config_keys":[],"health_url":None,"health_headers":lambda: {},"configured_keys":(),
   "tools":[{"name":"plutus_tool_slicer","label":"Tool Slicer","params":[("intent","Intent filter","text")]},
            {"name":"test_all_tools","label":"Full Tool Report","params":[]}]},

  # â•â•â•â•â•â•â•â• PUBLIC APIS â•â•â•â•â•â•â•â•
  {"id":"fal","label":"fal.ai","icon":"✨","tag":"ai","section":"public",
   "desc":"Cloud AI — FLUX, WAN, video generation",
   "config_keys":[("FAL_KEY","API Key","",True)],
   "health_url":None,"health_headers":lambda: {},"configured_keys":("fal_key",),
   "tools":[{"name":"fal_generate_image","label":"Generate (FLUX Schnell)","params":[("prompt","Prompt","text"),("model_id","Model ID","text"),("width","Width","number"),("height","Height","number")]},
            {"name":"fal_flux_pro","label":"FLUX Pro","params":[("prompt","Prompt","text"),("aspect_ratio","Aspect ratio","text")]},
            {"name":"fal_list_models_snippet","label":"Available Models","params":[]}]},

  {"id":"weather","label":"Weather (wttr.in)","icon":"🌤","tag":"utilities","section":"public",
   "desc":"Free weather — no key needed, defaults Hamburg",
   "config_keys":[("WEATHER_DEFAULT_LOCATION","Default city","Hamburg",False)],
   "health_url":None,"health_headers":lambda: {},"configured_keys":(),
   "tools":[{"name":"get_context","label":"Date + Time + Weather","params":[]},
            {"name":"weather_current","label":"Current Weather","params":[("location","City","text")]},
            {"name":"weather_forecast","label":"3-Day Forecast","params":[("location","City","text")]}]},

  {"id":"maps","label":"Maps (OpenStreetMap)","icon":"🗺","tag":"utilities","section":"public",
   "desc":"Free routing — no key needed",
   "config_keys":[],"health_url":None,"health_headers":lambda: {},"configured_keys":(),
   "tools":[{"name":"maps_distance","label":"Distance & Travel Time","params":[("origin","From","text"),("destination","To","text"),("mode","Mode","text")]}]},

  {"id":"websearch","label":"Web Search & Fetch","icon":"🔍","tag":"search","section":"public",
   "desc":"DuckDuckGo + page fetch — no key needed",
   "config_keys":[],"health_url":None,"health_headers":lambda: {},"configured_keys":(),
   "tools":[{"name":"web_search","label":"Search Web","params":[("query","Query","text"),("limit","Max","number")]},
            {"name":"web_fetch","label":"Fetch URL","params":[("url","URL","text")]}]},

  {"id":"wikipedia","label":"Wikipedia","icon":"📚","tag":"reference","section":"public",
   "desc":"Article summaries — MediaWiki API, no key",
   "config_keys":[],"health_url":None,"health_headers":lambda: {},"configured_keys":(),
   "tools":[{"name":"wikipedia_summary","label":"Article summary","params":[("title","Article title","text"),("lang","Language code","text")]}]},

  {"id":"currency","label":"Exchange rates","icon":"💱","tag":"finance","section":"public",
   "desc":"Frankfurter (ECB) — no key",
   "config_keys":[],"health_url":None,"health_headers":lambda: {},"configured_keys":(),
   "tools":[{"name":"currency_convert","label":"Convert amount","params":[("amount","Amount","number"),("from_currency","From (ISO)","text"),("to_currency","To (ISO)","text")]},
            {"name":"currency_rates","label":"Latest rates","params":[("base","Base currency","text")]}]},

  {"id":"google","label":"Google Custom Search","icon":"🔎","tag":"search","section":"public",
   "desc":"Programmable Search JSON API — set GOOGLE_API_KEY + GOOGLE_CSE_ID",
   "config_keys":[("GOOGLE_API_KEY","Google Cloud API key","",True),("GOOGLE_CSE_ID","Search engine ID (cx)","",False)],
   "health_url":None,"health_headers":lambda: {},"configured_keys":("google_api_key","google_cse_id"),
   "tools":[{"name":"google_search","label":"Google web search","params":[("query","Query","text"),("num","Max results","number")]}]},

  {"id":"smtp","label":"Email / Proton Bridge","icon":"📧","tag":"communication","section":"public",
   "desc":"Send via Proton Bridge SMTP or any SMTP",
   "config_keys":[("SMTP_HOST","SMTP Host","127.0.0.1",False),("SMTP_PORT","Port","1025",False),("SMTP_USERNAME","From address","",False),("SMTP_PASSWORD","Password","",True)],
   "health_url":None,"health_headers":lambda: {},"configured_keys":("smtp_host","smtp_username"),
   "tools":[{"name":"send_email","label":"Send Email","params":[("to","Recipient","text"),("subject","Subject","text"),("body","Body","text")]},
            {"name":"proton_bridge_status","label":"Bridge Status & Guide","params":[]}]},
]


OPEN_URL_BY_ID: dict[str, str] = {
    "jellyfin": "jellyfin_url",
    "sonarr": "sonarr_url",
    "radarr": "radarr_url",
    "lidarr": "lidarr_url",
    "jellyseerr": "jellyseerr_url",
    "qbittorrent": "qbittorrent_url",
    "immich": "immich_url",
    "homeassistant": "ha_url",
    "nextcloud": "nextcloud_url",
    "habitica": "habitica_url",
    "n8n": "n8n_url",
    "ntfy": "ntfy_url",
    "syncthing": "syncthing_url",
    "obsidian": "obsidian_url",
    "uptime_kuma": "uptime_kuma_url",
    "omv": "omv_url",
    "comfyui": "comfyui_url",
}

